In [1]:
#1. Business Problem
'''Predict the Strength of the building using various parameters'''

'Predict the Strength of the building using various parameters'

In [3]:
#2. Data Collection
import pandas as pd
import numpy as np
cement = pd.read_csv('Users/PREMR/OneDrive/Desktop/DATA SCIENCE/Automobile price data _Raw_')

In [4]:
#3. Data Understanding
cement.shape

(1030, 9)

In [5]:
cement.head()

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29

In [6]:
cement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cement        1030 non-null   float64
 1   slag          1030 non-null   float64
 2   ash           1030 non-null   float64
 3   water         1030 non-null   float64
 4   superplastic  1030 non-null   float64
 5   coarseagg     1030 non-null   float64
 6   fineagg       1030 non-null   float64
 7   age           1030 non-null   int64
 8   strength      1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.5 KB

In [ ]:
#4. Data Cleaning

In [7]:
X = cement.iloc[:,:8]

In [8]:
X.head()

   cement   slag    ash  water  superplastic  coarseagg  fineagg  age
0   141.3  212.0    0.0  203.5           0.0      971.8    748.5   28
1   168.9   42.2  124.3  158.3          10.8     1080.8    796.2   14
2   250.0    0.0   95.7  187.4           5.5      956.9    861.2   28
3   266.0  114.0    0.0  228.0           0.0      932.0    670.0   28
4   154.8  183.4    0.0  193.3           9.1     1047.4    696.7   28

In [9]:
y = cement.iloc[:,8:]

In [10]:
y.head(3)

   strength
0     29.89
1     23.51
2     29.22

In [11]:
#6. Split the data into Train and Test
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size = 0.2)

In [13]:
X_train.head(3)

     cement   slag  ash  water  superplastic  coarseagg  fineagg  age
194   154.8  183.4  0.0  193.3           9.1      877.2    867.7   28
32    145.7  172.6  0.0  181.9           3.4      985.8    816.8   28
136   166.8  250.2  0.0  203.5           0.0      975.6    692.6   90

In [14]:
y_train.head(3)

     strength
194     23.79
32      23.74
136     43.57

In [15]:
#7. Train the Model
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression

In [28]:
#model = LinearRegression()
model = DecisionTreeRegressor()

In [29]:
model.fit(X_train,y_train)

DecisionTreeRegressor()

In [30]:
#8. Test the Model
pred_strength = model.predict(X_test)

In [31]:
pred_strength

array([60.32, 26.92, 45.94, 40.76, 36.25, 69.66, 29.75, 17.37, 64.9 ,
       35.23, 36.97, 14.64, 33.72, 32.92, 36.15, 38.33, 45.85, 33.3 ,
       50.6 , 41.05, 21.95, 24.28, 14.7 , 12.46,  9.74, 17.6 , 43.06,
       36.45, 36.25, 36.15, 33.4 , 17.54,  4.9 , 29.93, 15.44, 53.52,
       34.57, 26.31, 19.11, 79.3 , 14.7 , 29.75, 35.3 , 33.56, 32.11,
       33.4 , 32.05, 58.16, 39.61, 26.06, 64.9 , 37.43, 31.64, 42.03,
       24.28, 13.62, 31.88, 81.75, 37.33, 42.7 , 27.74, 32.88,  9.45,
       27.04, 56.63, 13.54, 42.33, 33.06, 49.2 , 53.9 , 38.89,  9.69,
       26.77, 54.28, 17.54, 38.7 , 21.07, 19.99, 18.02, 59.3 , 17.44,
       22.5 , 15.69, 50.95, 44.39, 10.09, 55.64, 19.99, 41.68, 29.07,
       15.07, 18.42, 38.61, 62.94, 51.04, 50.95, 33.4 , 15.05, 18.02,
       26.92, 72.3 , 36.44, 39.3 , 36.45, 27.23, 39.6 , 28.68,  7.32,
       31.45, 15.03, 24.92, 18.02, 31.88, 71.7 , 55.9 , 52.91, 81.75,
       44.28, 39.78, 55.55, 25.45, 43.73, 39.3 , 32.05, 38.89, 10.76,
       34.4 , 11.85, 35.23, 27.74, 43.73,  9.62, 50.95, 25.12,  7.32,
       48.28, 64.3 , 40.93, 53.46, 30.39, 14.7 , 53.58, 51.72, 39.6 ,
       43.58, 33.69, 29.93, 63.53, 77.3 , 41.94, 38.2 , 31.64, 36.3 ,
       33.21, 21.54, 35.3 , 40.86, 39.09, 29.79, 16.5 , 21.78, 65.91,
        9.45, 32.05, 43.01, 15.09, 28.68, 24.29, 33.8 , 22.35, 33.7 ,
        8.06, 59.59, 18.42, 13.52, 55.51,  9.62, 22.49, 42.55, 31.03,
       41.54, 77.3 , 37.68,  6.47, 47.22, 40.86, 50.77,  9.87, 35.86,
       31.65, 26.85, 57.21,  6.47, 33.66, 12.46, 43.06, 29.22, 79.3 ,
       66.78, 52.45, 25.56, 25.56, 31.18, 12.79, 21.91, 39.15])

In [32]:
y_test.head(5)

     strength
216     66.42
471     26.92
247     40.15
445     40.56
878     38.41

In [22]:
#9. Evaluate the Model
from sklearn.metrics import r2_score

In [33]:
#Test Accuracy
r2_score(pred_strength, y_test)

0.8173099977217089

In [34]:
train_strength = model.predict(X_train)

In [35]:
#Train Accuracy
r2_score(train_strength, y_train)

0.9992230900825424

In [ ]:
#10. Model Deployment

1. Why Decision Tree?
2. Why our Model accuracy is low?
3. How to improve the model accuracy? what may be the reason?
4. What is happening inside Decision Tree?
5. How we can trust it?

Model Accuracy is Dependent on Three Parameters
1. Change in Algorithm
2. Change in Sample
3. Change in Features